name: Build HTML documentation

on:
  [push, pull_request]

jobs:
  build:
    name: Build HTML documentation
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        name: Install Python
        with:
          python-version: '3.10'

      - name: Install documentation dependencies
        run: |
          python -m pip install -r doc/requirements.txt

      - name: Install QuTiP from GitHub
        run: |
          python -m pip install git+https://github.com/qutip/qutip.git@master
          python -c 'import qutip; qutip.about()'

      - name: Install qutip-jax from GitHub
        run: |
          python -m pip install jax jax[cpu]
          python -m pip install .[full]
          python -c 'import qutip_jax; print(qutip_jax.__version__)'

      - name: Build documentation
        working-directory: doc
        run: |
          make html SPHINXOPTS="-W --keep-going -T"

      - name: Upload built files
        uses: actions/upload-artifact@v4
        with:
          name: qutip-jax_html_docs
          path: doc/_build/html/*
          if-no-files-found: error
