name: Update version on PR merge
on:
  pull_request:
    branches:
      - master
    types: closed

jobs:
  update_date:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: Increment VERSION
        run: |
          version="$(cat VERSION)"; python -c "b, n = '$version'.split('v'); print('v'.join([b, str(int(n)+1)]))" > VERSION
      - name: Add commit
        run: |
          git config --global user.email "Version_Incrementer@gh_bot"
          git config --global user.name "Version Incrementer"
          git commit -a -m "Increment version"
          git push
